server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/order_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${defaultZone:http://localhost:8671/eureka}
  server:
    port: 8671

resilience4j:
  retry:
  instances:
    product-service-retry:
      max-attempts: 3
      wait-duration: 5s
      enable-exponential-backoff: true
      exponential-backoff-multiplier: 2
  circuitbreaker:
    instances:
      product-service-circuit-breaker:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60
